### PR TITLE
Fix requirements dependencies

### PR DESCRIPTION
**Pull request by Delgan**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

Hi.

It was reported to me some error while trying to use `loguru` within a `conda` environment: https://github.com/Delgan/loguru/issues/147

I don't know much about Anaconda, but I noticed the `meta.yaml` used outdated requirements compared to the upstream `v0.3.2` of `loguru`.  Hopefully, this PR should solves this. :)

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-smithy please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@Delgan Thanks for putting in the PR, this should solve the issue. Weirdly CI doesn't seem to run on the last commit, otherwise this would be ready to be merged.

**Comment by Delgan** [comment]
@xhochy Yeah, it seems `win` CI build is failing because it can't find the `win32_setctime` dependency. I don't know much about Cuda. Do I also need to create a new `win32-setctime-feedstock` package and publish it to `conda-forge`?

**Comment by xhochy** [comment]
@Delgan I opened a PR https://github.com/conda-forge/staged-recipes/pull/9766 to add it to conda-forge, feel free to ask for maintainer rights there, too.

**Comment by xhochy** [comment]
@conda-forge-admin, please restart ci

**Comment by xhochy** [comment]
@conda-forge-admin, please restart ci

**Pull request closed without merging**
